SCHEMA = r"""
CREATE TABLE IF NOT EXISTS snapshots(snapshot_id VARCHAR PRIMARY KEY, source VARCHAR, endpoint VARCHAR, retrieved_at_utc TIMESTAMP, request_parameters JSON, http_status INTEGER, response_hash VARCHAR, record_count BIGINT, error VARCHAR);
CREATE TABLE IF NOT EXISTS markets(market_id VARCHAR PRIMARY KEY, event_id VARCHAR, condition_id VARCHAR, question VARCHAR, slug VARCHAR, category VARCHAR, yes_token_id VARCHAR, no_token_id VARCHAR, open_time TIMESTAMP, close_time TIMESTAMP, resolution_time TIMESTAMP, resolved_token VARCHAR, status VARCHAR, volume DOUBLE, liquidity DOUBLE, unique_traders BIGINT, eligible BOOLEAN, eligibility_reason VARCHAR, data_quality_flags VARCHAR, raw_snapshot_id VARCHAR, created_at TIMESTAMP, updated_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS fills(fill_id VARCHAR PRIMARY KEY, transaction_hash VARCHAR, log_index VARCHAR, wallet VARCHAR, market_id VARCHAR, condition_id VARCHAR, token_id VARCHAR, outcome VARCHAR, side VARCHAR, timestamp_utc TIMESTAMP, price DOUBLE, size DOUBLE, notional DOUBLE, signed_exposure DOUBLE, source_snapshot_id VARCHAR, data_quality_flags VARCHAR, UNIQUE(transaction_hash, log_index));
CREATE TABLE IF NOT EXISTS price_observations(market_id VARCHAR, token_id VARCHAR, timestamp_utc TIMESTAMP, price DOUBLE, resolution_seconds INTEGER, source_snapshot_id VARCHAR, PRIMARY KEY(market_id, token_id, timestamp_utc));
CREATE TABLE IF NOT EXISTS episodes(episode_id VARCHAR PRIMARY KEY, wallet VARCHAR, market_id VARCHAR, direction VARCHAR, entry_time TIMESTAMP, exit_time TIMESTAMP, entry_price DOUBLE, exit_price DOUBLE, entry_notional DOUBLE, peak_open_notional DOUBLE, total_notional DOUBLE, trade_count INTEGER, persistence DOUBLE, resolved BOOLEAN, realized_pnl DOUBLE, data_quality_flags VARCHAR, episode_version VARCHAR);
CREATE TABLE IF NOT EXISTS episode_features(episode_id VARCHAR PRIMARY KEY, wallet_age_days DOUBLE, prior_episode_count INTEGER, prior_volume DOUBLE, prior_notional_median DOUBLE, prior_notional_p95 DOUBLE, prior_win_rate DOUBLE, prior_realized_pnl DOUBLE, prior_category_count INTEGER, prior_market_count INTEGER, episode_notional DOUBLE, max_open_exposure DOUBLE, market_volume_share DOUBLE, market_size_percentile DOUBLE, wallet_size_percentile DOUBLE, market_robust_z DOUBLE, wallet_robust_z DOUBLE, lead_hours DOUBLE, signed_move_15m DOUBLE, signed_move_1h DOUBLE, signed_move_6h DOUBLE, signed_move_24h DOUBLE, timing_percentile DOUBLE, timestamp_sensitivity VARCHAR, market_order_imbalance DOUBLE, wallet_directional_share DOUBLE, pre_move_volume_share DOUBLE, n_bets INTEGER, expected_wins DOUBLE, actual_wins DOUBLE, excess_wins DOUBLE, expected_pnl DOUBLE, actual_pnl DOUBLE, profit_z DOUBLE, p_value DOUBLE, q_value DOUBLE, raw_anomaly_score DOUBLE, anomaly_percentile DOUBLE, top_3_contributors VARCHAR, model_version VARCHAR, feature_version VARCHAR, s1 DOUBLE, s2 DOUBLE, s3 DOUBLE, s4 DOUBLE, s5 DOUBLE, q1 DOUBLE, q2 DOUBLE, q3 DOUBLE, q4 DOUBLE, q5 DOUBLE, suppression_reasons VARCHAR);
CREATE TABLE IF NOT EXISTS public_events(event_id VARCHAR PRIMARY KEY, market_id VARCHAR, event_time_utc TIMESTAMP, earliest_time_utc TIMESTAMP, latest_time_utc TIMESTAMP, original_timestamp TIMESTAMP, headline VARCHAR, source_url VARCHAR, source_type VARCHAR, confidence VARCHAR, annotator VARCHAR, verified BOOLEAN, rejected BOOLEAN DEFAULT FALSE, verification_time TIMESTAMP, created_at TIMESTAMP, updated_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS alerts(alert_id VARCHAR PRIMARY KEY, episode_id VARCHAR UNIQUE, s1 DOUBLE, s2 DOUBLE, s3 DOUBLE, s4 DOUBLE, s5 DOUBLE, composite_score DOUBLE, valid_module_count INTEGER, alert_band VARCHAR, reliability DOUBLE, top_evidence VARCHAR, counterevidence VARCHAR, data_quality_flags VARCHAR, feature_version VARCHAR, model_version VARCHAR, created_at TIMESTAMP, status VARCHAR);
CREATE TABLE IF NOT EXISTS reviews(review_id VARCHAR PRIMARY KEY, alert_id VARCHAR, reviewer VARCHAR, reviewed_at TIMESTAMP, disposition VARCHAR, notes VARCHAR, second_review_required BOOLEAN, second_reviewer VARCHAR, second_review_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS pipeline_runs(run_id VARCHAR PRIMARY KEY, started_at TIMESTAMP, completed_at TIMESTAMP, command VARCHAR, status VARCHAR, markets_processed INTEGER, fills_processed INTEGER, price_points_processed INTEGER, episodes_created INTEGER, alerts_created INTEGER, error_count INTEGER, git_commit VARCHAR, config_hash VARCHAR);
CREATE TABLE IF NOT EXISTS ingestion_watermarks(source VARCHAR PRIMARY KEY, watermark VARCHAR, updated_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS backtest_results(run_id VARCHAR, metric VARCHAR, value DOUBLE, details VARCHAR, created_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS kalshi_weather_markets(ticker VARCHAR PRIMARY KEY, event_ticker VARCHAR, series_ticker VARCHAR, title VARCHAR, subtitle VARCHAR, status VARCHAR, open_time TIMESTAMP, close_time TIMESTAMP, last_price DOUBLE, volume DOUBLE, open_interest DOUBLE, result VARCHAR, updated_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS kalshi_weather_trades(trade_id VARCHAR PRIMARY KEY, ticker VARCHAR, timestamp_utc TIMESTAMP, outcome_side VARCHAR, book_side VARCHAR, price DOUBLE, contracts DOUBLE, notional DOUBLE, size_percentile DOUBLE, robust_z DOUBLE, anomaly_score DOUBLE, is_anomaly BOOLEAN, is_block_trade BOOLEAN, k1_size DOUBLE, k2_price DOUBLE, k3_burst DOUBLE, k4_concentration DOUBLE, k5_behavior DOUBLE);
CREATE TABLE IF NOT EXISTS market_discovery_audit(audit_id VARCHAR PRIMARY KEY, source VARCHAR, discovered_at TIMESTAMP, external_id VARCHAR, title VARCHAR, decision VARCHAR, reason VARCHAR, weather_type VARCHAR);
CREATE TABLE IF NOT EXISTS authoritative_weather_sources(source_key VARCHAR PRIMARY KEY, name VARCHAR, url VARCHAR, purpose VARCHAR, updated_at TIMESTAMP);
CREATE TABLE IF NOT EXISTS weather_news_items(item_id VARCHAR PRIMARY KEY, source_name VARCHAR, source_type VARCHAR, title VARCHAR, url VARCHAR, published_at TIMESTAMP, retrieved_at TIMESTAMP, source_domain VARCHAR, weather_type VARCHAR, location_text VARCHAR, reliability DOUBLE, raw_snapshot_id VARCHAR);
"""
